#!/bin/bash

#------------Change only this line to reflect current directory--------------
workingDir=/home/pi/portManager/

logLoc=tmp/portManager.log
logLoc="$workingDir$logLoc"
dataFile=tmp/openPorts.data
dataFile="$workingDir$dataFile"

function log {
	date=$(date)
	echo "$date ---$@---" >> $logLoc
}

function setupPorts {
	log "Setting ports"

#---change these lines for your port forwarding options-------------------
#---Usage: upnpc -a <IP> <InteralPort> <ExternalPort> <Protocol>-----------
	log "Returned:$(upnpc -a 192.168.0.15 22 5555 TCP)"
	log "Returned:$(upnpc -a 192.168.0.15 8080 666 TCP)"
}

echo "" > $logLoc
date=$(date)
echo "$date ----System Start----" >> $logLoc

while true; do
	upnpc -l > $dataFile

	data=$(grep "libminiupnpc" $dataFile)
#	log "RawData___$data"

	if [[ $data != *""* ]]
	then
		log "Ports not setup..."
		setupPorts
	fi
	sleep 5m
done
