#!/bin/bash

#------------Change only this line to reflect current directory--------------
workingDir="/home/pi/portManager/"

logLoc="tmp/portManager-$(date -I)--$(date +%M%N).log"
logLoc="$workingDir$logLoc"
dataFile="tmp/openPorts.data"
dataFile="$workingDir$dataFile"
lanIP=$(/sbin/ip -4 -o addr show dev eth0| awk '{split($4,a,"/");print a[1]}')

function log {
	date="$(date)"
	echo "$date ---$@---" >> $logLoc
}

function setupPorts {
	log "Setting ports"

#---change these lines for your port forwarding options-------------------
#---Usage: upnpc -a <IP> <InteralPort> <ExternalPort> <Protocol>-----------
	log "Returned:$(upnpc -a $lanIP 22 5555 TCP)"
	log "Returned:$(upnpc -a $lanIP 8080 666 TCP)"
}

echo "" > $logLoc
date=$(date)
echo "$date ----System Start----" >> $logLoc

while true; do
	upnpc -l > $dataFile

	data=$(grep "libminiupnpc" $dataFile)
#	log "RawData___$data"

	if [[ $data != *"$lanIP"* ]]
	then
		log "Ports not setup..."
		setupPorts
		pushbullet 'New WAN IP: '$(curl -s http://whatismijnip.nl |cut -d " " -f 5)
	fi
	sleep 5m
done
