#!/bin/sh

# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
set -e

# Must be a valid filename
NAME=portmanager
PIDFILE=/var/run/$NAME.pid
#This is the command to be run, give the full pathname
DAEMON=/home/pi/portManager/portmanager
DAEMON_OPTS=""

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
. /lib/lsb/init-functions

case "$1" in
  start)
	start-stop-daemon --start --verbose --background --pidfile $PIDFILE --make-pidfile --exec $DAEMON
        status_of_proc -p $PIDFILE "$DAEMON" "$NAME" && exit 0 || exit $?
	echo "."
	;;
  stop)
	start-stop-daemon --stop --verbose --oknodo --pidfile $PIDFILE
        echo "."
	;;
  restart)
	start-stop-daemon --stop --verbose --oknodo --retry 30 --pidfile $PIDFILE
	start-stop-daemon --start --verbose --background --pidfile $PIDFILE --make-pidfile --exec $DAEMON
	status_of_proc -p $PIDFILE "$DAEMON" "$NAME" && exit 0 || exit $?
	echo "."
	;;

  status)
	status_of_proc -p $PIDFILE "$DAEMON" "$NAME" && exit 0 || exit $?
	;;
  *)
	echo "Usage: "$1" {start|stop|restart}"
	exit 1
esac

exit 0
